services:
  mihomo:
    build: 
      context: .
    network_mode: host
    restart: always
    pid: host
    ipc: host
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./data:/root/.config/mihomo/
      - /dev/net/tun:/dev/net/tun
      # 共享host的时间环境
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DIRECT_DOMAIN=www.neofeed.org # 这个域名走直连，避免被劫持导致无法访问订阅地址
      - SUBSCRIBE="https://example.com/subscribe"
